programa
{
	
	funcao inicio()
	{
		escreva("Olá, mundo!")	
	}
}

/*

Este código simples em portugol studio (.POR) está aqui apenas
porque o GitHub não reconhece as extensões .ALG do VisuAlg como
escritas em portugol. Assim, criando um pequeno trecho de código
com o portugol studio conseguimos fazer com que o github reconheça
esse repositório como um repositório da linguagem portugol.

*/