Algoritmo "Area de retangulo"
// Unidade I : Exercício a)
// Autor(a)    : Antonio Sérgio
// Data atual  : 12/11/2022
// Ver. VisuAlg : 3.0.7

Var
   base : inteiro
   altura : inteiro
Inicio
      escreval("---")
      escreval("CALCULAR ÁREA DE UM RETÂNGULO")
      escreval("---")
      escreval(" ")
      escreval("Digite o tamanho da base: ")
      leia(base)
      escreval("Digite o tamanho da altura: ")
      leia(altura)
      escreva(base*altura)

Fimalgoritmo